import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import test from "node:test";
import {
  inspectTurkeyParentProvenance,
  verifyTurkeyParentProvenance
} from "../packages/generators/dist/turkey-adm3.mjs";
import {
  generateParentProvenanceReports,
  isParentProvenanceAuditCliEntry
} from "./tr-parent-provenance-audit.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FIXTURE_PARENT = path.join(
  REPO_ROOT,
  "packages/generators/test/fixtures/tr-parent-provenance/canonical-parent-snapshot.json"
);
const NATIONAL_CATALOG = path.join(REPO_ROOT, "datasets/sources/TR/national.json");
const AUDIT_SCRIPT = path.join(REPO_ROOT, "scripts/tr-parent-provenance-audit.mjs");

test("fixture parent snapshot disagrees with HDX catalog provider lock", async () => {
  const catalog = JSON.parse(await readFile(NATIONAL_CATALOG, "utf8"));
  const parentDataset = JSON.parse(await readFile(FIXTURE_PARENT, "utf8"));
  const inspection = await inspectTurkeyParentProvenance({
    parentDataset,
    catalog: {
      provider: catalog.provider,
      sourceId: catalog.sourceId,
      sha256: catalog.sha256,
      byteSize: catalog.byteSize,
      levels: catalog.levels
    },
    requireFullParentInventory: false
  });
  assert.equal(inspection.providerMetadataStatus, "CATALOG_LOCK_DIFFERS_FROM_PARENT_POLYGONS");
  assert.equal(inspection.observedDominantProvider, "geoboundaries");
  assert.equal(inspection.catalogProvider, "hdx-cod-ab");
  assert.equal(verifyTurkeyParentProvenance(inspection).authorizedForNationalBuild, false);
});

test("importing audit module does not execute CLI entry", () => {
  assert.equal(isParentProvenanceAuditCliEntry(["node", "/some/other-script.mjs"]), false);
});

test("CLI audit entry exits non-zero for provider mismatch fixture", async () => {
  const outputDir = await mkdtemp(path.join(os.tmpdir(), "territory-prov-audit-cli-"));
  try {
    const result = spawnSync(
      process.execPath,
      [
        AUDIT_SCRIPT,
        "--parent-dataset",
        FIXTURE_PARENT,
        "--output-dir",
        outputDir,
        "--allow-missing-byte-evidence"
      ],
      { cwd: REPO_ROOT, encoding: "utf8" }
    );
    assert.notEqual(result.status, 0, result.stderr || result.stdout);
    const payload = JSON.parse(result.stdout);
    assert.equal(payload.ok, false);
    assert.equal(payload.providerMetadataStatus, "CATALOG_LOCK_DIFFERS_FROM_PARENT_POLYGONS");
    const lineage = JSON.parse(await readFile(path.join(outputDir, "parent-lineage.json"), "utf8"));
    assert.equal(lineage.auditReportComplete, false);
  } finally {
    await rm(outputDir, { recursive: true, force: true });
  }
});

test("generateParentProvenanceReports import path does not claim success without byte evidence", async () => {
  const outputDir = await mkdtemp(path.join(os.tmpdir(), "territory-prov-audit-import-"));
  try {
    const { auditReportComplete, verification } = await generateParentProvenanceReports({
      outputDir,
      parentDatasetPath: FIXTURE_PARENT,
      requireAuditByteEvidence: true
    });
    assert.equal(verification.authorizedForNationalBuild, false);
    assert.equal(auditReportComplete, false);
  } finally {
    await rm(outputDir, { recursive: true, force: true });
  }
});

test("full tracked parent dataset audit when local generated bytes exist", async (t) => {
  const parentDatasetPath = path.join(REPO_ROOT, "datasets/generated/countries/TR/dataset.json");
  if (!existsSync(parentDatasetPath)) {
    t.skip(
      "datasets/generated/countries/TR/dataset.json is gitignored; run locally after data build"
    );
  }
  const { inspection, auditReportComplete } = await generateParentProvenanceReports({
    outputDir: path.join(REPO_ROOT, "reports/tr-adm3/provenance"),
    parentDatasetPath,
    requireAuditByteEvidence: false
  });
  assert.equal(inspection.providerMetadataStatus, "CATALOG_LOCK_DIFFERS_FROM_PARENT_POLYGONS");
  assert.equal(auditReportComplete, false);
});
