import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import {
  inspectTurkeyParentProvenance,
  verifyTurkeyParentProvenance
} from "../packages/generators/dist/turkey-adm3.mjs";
import { generateParentProvenanceReports } from "./tr-parent-provenance-audit.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FIXTURE_PARENT = path.join(
  REPO_ROOT,
  "packages/generators/test/fixtures/tr-parent-provenance/canonical-parent-snapshot.json"
);
const NATIONAL_CATALOG = path.join(REPO_ROOT, "datasets/sources/TR/national.json");

test("fixture parent snapshot disagrees with HDX catalog provider lock", async () => {
  const catalog = JSON.parse(await readFile(NATIONAL_CATALOG, "utf8"));
  const parentDataset = JSON.parse(await readFile(FIXTURE_PARENT, "utf8"));
  const inspection = await inspectTurkeyParentProvenance({
    parentDataset,
    catalog: {
      provider: catalog.provider,
      sourceId: catalog.sourceId,
      sha256: catalog.sha256,
      byteSize: catalog.byteSize,
      levels: catalog.levels
    }
  });
  assert.equal(inspection.lineageStatus, "CATALOG_LOCK_DIFFERS_FROM_PARENT_POLYGONS");
  assert.equal(inspection.observedDominantProvider, "geoboundaries");
  assert.equal(inspection.catalogProvider, "hdx-cod-ab");
  assert.equal(verifyTurkeyParentProvenance(inspection).ok, false);
});

test("full tracked parent dataset audit when local generated bytes exist", async (t) => {
  const parentDatasetPath = path.join(REPO_ROOT, "datasets/generated/countries/TR/dataset.json");
  if (!existsSync(parentDatasetPath)) {
    t.skip(
      "datasets/generated/countries/TR/dataset.json is gitignored; run locally after data build"
    );
  }
  const { inspection, verification } = await generateParentProvenanceReports({
    outputDir: path.join(REPO_ROOT, "reports/tr-adm3/provenance"),
    parentDatasetPath
  });
  assert.equal(inspection.lineageStatus, "CATALOG_LOCK_DIFFERS_FROM_PARENT_POLYGONS");
  assert.equal(verification.ok, false);
});
